config:
    session: ./common/sessions.json
    commodity: ./common/stk_comms.json
    contract: ./common/stocks.json
    risk: false
    profile: fixTest
    platform_settings:
        windows:
            path_separator: "\\"
            socket_impl: "winsock"
        linux:
            path_separator: "/"
            socket_impl: "posix"
        macos:
            path_separator: "/"
            socket_impl: "posix"

fixTest:
    BeginString: "FIXT.1.1"  # FIX传输协议版本
    DefaultApplVerID: "FIX.5.0"  # FIX应用层版本
    SenderCompID: "CLIENT1"  # 发送方标识
    TargetCompID: "BROKER"  # 接收方标识
    HeartBtInt: 30  # 心跳间隔（秒）
    ResetSeqNumFlag: true  # 是否重置序号标志
    DataDictionary: "./config/FIX42.xml"  # 数据字典文件路径
    StartTime: "09:00:00"  # 交易时段开始时间
    EndTime: "15:00:00"  # 交易时段结束时间
    SocketConnectHost: "127.0.0.1"  # 连接地址
    SocketConnectPort: 5001  # 连接端口
    Username: "testuser"  # 用户名
    Password: "testpass"  # 密码
    LogonTimeout: 10  # 登录超时时间（秒）
    ReconnectInterval: 30  # 重连间隔（秒）
    SendBufferSize: 512  # 发送缓冲区大小（KB）
    ReceiveBufferSize: 512  # 接收缓冲区大小（KB）
    ValidateFieldsOutOfOrder: false  # 是否校验字段顺序
    ValidateFieldsHaveValues: true  # 是否校验字段值
    ValidateUserDefinedFields: false  # 是否校验用户自定义字段
